#ifndef SLEIPNIR_SLEIPNIR_MATH_H
#define SLEIPNIR_SLEIPNIR_MATH_H

#include "sleipnir_macros.h"

SLEIPNIR_START_CPP_NAMESPACE

int spAdd(int x, int y);

SLEIPNIR_END_CPP_NAMESPACE

#endif //SLEIPNIR_SLEIPNIR_MATH_H
